export const EMAIL_REPOSITORY_PROVIDE = Symbol('EMAIL_REPOSITORY_PROVIDE');
export const USER_EMAIL_REPOSITORY_PROVIDE = Symbol('USER_EMAIL_REPOSITORY_PROVIDE');
export const EMAIL_SERVICE_PROVIDE = Symbol('EMAIL_SERVICE_PROVIDE');
export const ADD_USER_EMAIL_USE_CASE_PROVIDE = Symbol('ADD_USER_EMAIL_USE_CASE_PROVIDE');
export const LIST_USER_EMAILS_USE_CASE_PROVIDE = Symbol('LIST_USER_EMAILS_USE_CASE_PROVIDE');
export const REMOVE_USER_EMAIL_USE_CASE_PROVIDE = Symbol('REMOVE_USER_EMAIL_USE_CASE_PROVIDE');
export const SEND_EMAIL_VERIFICATION_USE_CASE_PROVIDE = Symbol(
  'SEND_EMAIL_VERIFICATION_USE_CASE_PROVIDE',
);
export const VERIFY_EMAIL_CODE_USE_CASE_PROVIDE = Symbol('VERIFY_EMAIL_CODE_USE_CASE_PROVIDE');
