export const COMPANY_REPOSITORY_PROVIDE = 'COMPANY_REPOSITORY_PROVIDE';
export const COMPANY_SERVICE_PROVIDE = 'COMPANY_SERVICE_PROVIDE';
export const COMPANY_CREATE_USE_CASE_PROVIDE = 'COMPANY_CREATE_USE_CASE_PROVIDE';
export const COMPANY_LIST_USER_COMPANIES_USE_CASE_PROVIDE = 'COMPANY_LIST_USER_COMPANIES_USE_CASE_PROVIDE';
export const COMPANY_ADD_MEMBER_USE_CASE_PROVIDE = 'COMPANY_ADD_MEMBER_USE_CASE_PROVIDE';
