export const PHONE_REPOSITORY_PROVIDE = Symbol('PHONE_REPOSITORY_PROVIDE');
export const USER_PHONE_REPOSITORY_PROVIDE = Symbol('USER_PHONE_REPOSITORY_PROVIDE');
export const PHONE_SERVICE_PROVIDE = Symbol('PHONE_SERVICE_PROVIDE');
export const ADD_USER_PHONE_USE_CASE_PROVIDE = Symbol('ADD_USER_PHONE_USE_CASE_PROVIDE');
export const LIST_USER_PHONES_USE_CASE_PROVIDE = Symbol('LIST_USER_PHONES_USE_CASE_PROVIDE');
export const REMOVE_USER_PHONE_USE_CASE_PROVIDE = Symbol('REMOVE_USER_PHONE_USE_CASE_PROVIDE');
export const SEND_PHONE_VERIFICATION_USE_CASE_PROVIDE = Symbol(
  'SEND_PHONE_VERIFICATION_USE_CASE_PROVIDE',
);
export const VERIFY_PHONE_CODE_USE_CASE_PROVIDE = Symbol('VERIFY_PHONE_CODE_USE_CASE_PROVIDE');
