export const USER_REPOSITORY_PROVIDE = 'USER_REPOSITORY_PROVIDE';
export const USER_INFRASTRUCTURE_SERVICE_PROVIDE = 'USER_INFRASTRUCTURE_SERVICE_PROVIDE';
export const USER_CREATE_USE_CASE_PROVIDE = 'USER_CREATE_USE_CASE_PROVIDE';
export const FIND_USER_BY_ID_USE_CASE_PROVIDE = 'FIND_USER_BY_ID_USE_CASE_PROVIDE';
export const FIND_USER_BY_KEYCLOAK_ID_USE_CASE_PROVIDE = 'FIND_USER_BY_KEYCLOAK_ID_USE_CASE_PROVIDE';
export const UPDATE_USER_USE_CASE_PROVIDE = 'UPDATE_USER_USE_CASE_PROVIDE';
export const DELETE_USER_USE_CASE_PROVIDE = 'DELETE_USER_USE_CASE_PROVIDE';
export const USER_SERVICE_PROVIDE = 'USER_SERVICE_PROVIDE';
