export const ACCOUNT_BLOCK_GET_STATUS_USE_CASE = 'ACCOUNT_BLOCK_GET_STATUS_USE_CASE';
export const ACCOUNT_BLOCK_CREATE_USE_CASE = 'ACCOUNT_BLOCK_CREATE_USE_CASE';
export const ACCOUNT_BLOCK_RESOLVE_USE_CASE = 'ACCOUNT_BLOCK_RESOLVE_USE_CASE';
export const ACCOUNT_BLOCK_LIST_USE_CASE = 'ACCOUNT_BLOCK_LIST_USE_CASE';
