export enum UserErrorCode {
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  DUPLICATE_CPF = 'DUPLICATE_CPF',
  DUPLICATE_RG = 'DUPLICATE_RG',
  DUPLICATE_KEYCLOAK_ID = 'DUPLICATE_KEYCLOAK_ID',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INVALID_USER_TYPE = 'INVALID_USER_TYPE',
  USER_NOT_DELETED = 'USER_NOT_DELETED',
}
