export const DEVICE_TOKEN_REPOSITORY_PROVIDE = 'DEVICE_TOKEN_REPOSITORY_PROVIDE';
export const DEVICE_TOKEN_REGISTER_USE_CASE_PROVIDE = 'DEVICE_TOKEN_REGISTER_USE_CASE_PROVIDE';
export const DEVICE_TOKEN_SERVICE_PROVIDE = 'DEVICE_TOKEN_SERVICE_PROVIDE';
